=== jiuzhuaxiong/esdk_elte_player/platform/SDK/conf/deploy_policy.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
file      : \code\src\platform\modules\sca\deploy_policy.xsd
install   : \install\conf\deploy_policy.xsd
author    : ZhongWei
created   : 2012/10/26 13:30
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:svcmgr="http://www.td-tech.com/ubp/platform/svcmgr/xml"
            targetNamespace="http://www.td-tech.com/ubp/platform/svcmgr/xml">

  <xsd:complexType name="CoreInfo">
    <xsd:attribute name="core_count" type="xsd:string" use="required"/>
    <xsd:attribute name="value" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="Service">
  	<xsd:sequence>
      <xsd:element name="CoreInfo" type="svcmgr:CoreInfo" maxOccurs="unbounded" minOccurs="0"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>  
  
  <xsd:complexType name="ServiceMode">
  	<xsd:sequence>
      <xsd:element name="Service" type="svcmgr:Service" maxOccurs="unbounded" minOccurs="0"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>    
  </xsd:complexType>              

  <xsd:complexType name="ServiceModeInfo">
    <xsd:sequence>
      <xsd:element name="ServiceMode" type="svcmgr:ServiceMode" maxOccurs="unbounded"/>
    </xsd:sequence>    
  </xsd:complexType>            
  
  <xsd:complexType name="ServiceTypeA">
    <xsd:attribute name="type" type="xsd:string" use="required"/>
    <xsd:attribute name="defaultname" type="xsd:string" use="required"/>
    <xsd:attribute name="pubport" type="xsd:integer" use="required"/>
    <xsd:attribute name="dealport" type="xsd:integer" use="required"/>
    <xsd:attribute name="ip_type" type="xsd:integer" use="required"/>
  </xsd:complexType> 

  <xsd:complexType name="ServiceTypeInfo">
    <xsd:sequence>
      <xsd:element name="ServiceTypeA" type="svcmgr:ServiceTypeA" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="port_offset" type="xsd:integer" use="required"/>
  </xsd:complexType>  

  <xsd:complexType name="HostCfg">
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="value" type="xsd:string" use="required"/>
  </xsd:complexType>
    
  <xsd:complexType name="HostInfo">
    <xsd:sequence>
      <xsd:element name="HostCfg" type="svcmgr:HostCfg" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="DBInit" type="xsd:boolean" />    
  </xsd:complexType>
  
  <xsd:complexType name="ServicePolicy">
  	   <xsd:sequence>
          <xsd:element name="HostInfo" type="svcmgr:HostInfo" />
          <xsd:element name="ServiceTypeInfo" type="svcmgr:ServiceTypeInfo" />
          <xsd:element name="ServiceModeInfo" type="svcmgr:ServiceModeInfo" />
       </xsd:sequence>
  </xsd:complexType>
  
  <xsd:element name="ServicePolicy" type="svcmgr:ServicePolicy"/>
</xsd:schema>

=== jiuzhuaxiong/esdk_elte_player/platform/SDK/conf/deploy_policy.xml
<?xml version="1.0" encoding="utf-8"?>
<svcmgr:ServicePolicy xmlns:svcmgr="http://www.td-tech.com/ubp/platform/svcmgr/xml"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:schemaLocation="http://www.td-tech.com/ubp/platform/svcmgr/xml deploy_policy.xsd">

  <HostInfo>
    <HostCfg name="host_name"
             value="$ubp_local_host_name" />
    <HostCfg name="service_mode"
             value="MDC" />
    <HostCfg name="cpu_cores"
             value="16" />
    <HostCfg name="om_ip"
             value="$ubp_local_ip" />
    <HostCfg name="med_ip"
             value="$ubp_local_ip" />
    <HostCfg name="master_ip"
             value="" />
    <HostCfg name="veristas_mode"
             value="NO_SET" />
    <HostCfg name="bcc_ip"
             value="" />
    <!--HostCfg name="dev_db_ip" value="10.121.87.8"/-->	     
  </HostInfo>
  <ServiceTypeInfo port_offset="0">
    <ServiceTypeA type="daem_agent"
                  defaultname="ubp_daem"
                  pubport="20001"
                  dealport="20002"
                  ip_type="0" />
    <ServiceTypeA type="cm_agent"
                  defaultname="ubp_cm"
                  pubport="20100"
                  dealport="20005"
                  ip_type="0" />
    <ServiceTypeA type="fm_agent"
                  defaultname="ubp_fm"
                  pubport="20007"
                  dealport="20008"
                  ip_type="0" />
    <ServiceTypeA type="lm_agent"
                  defaultname="ubp_lm"
                  pubport="20010"
                  dealport="20011"
                  ip_type="0" />
    <ServiceTypeA type="mon_agent"
                  defaultname="ubp_monitor"
                  pubport="20013"
                  dealport="20014"
                  ip_type="0" />
    <ServiceTypeA type="bcc_agent"
                  defaultname="ubp_bcc"
                  pubport="22001"
                  dealport="22002"
                  ip_type="0" />
    <ServiceTypeA type="bdc_agent"
                  defaultname="ubp_bdc01"
                  pubport="22004"
                  dealport="22005"
                  ip_type="1" />
    <ServiceTypeA type="bdc_agent"
                  defaultname="ubp_bdc02"
                  pubport="22006"
                  dealport="22007"
                  ip_type="1" />
    <ServiceTypeA type="bdc_agent"
                  defaultname="ubp_bdc03"
                  pubport="22008"
                  dealport="22009"
                  ip_type="1" />
    <ServiceTypeA type="bdc_agent"
                  defaultname="ubp_bdc04"
                  pubport="22010"
                  dealport="22011"
                  ip_type="1" />
    <ServiceTypeA type="bdc_agent"
                  defaultname="ubp_bdc05"
                  pubport="22012"
                  dealport="22013"
                  ip_type="1" />
    <ServiceTypeA type="bdc_agent"
                  defaultname="ubp_bdc06"
                  pubport="22014"
                  dealport="22015"
                  ip_type="1" />
    <ServiceTypeA type="dec_vgw_agent"
                  defaultname="ubp_dec_vgw"
                  pubport="22022"
                  dealport="22023"
                  ip_type="0" />
    <ServiceTypeA type="gis_agent"
                  defaultname="ubp_gis"
                  pubport="22028"
                  dealport="22029"
                  ip_type="0" />
    <ServiceTypeA type="mrs_mgr_agent"
                  defaultname="ubp_mrs_mgr"
                  pubport="22049"
                  dealport="22050"
                  ip_type="0" />
    <ServiceTypeA type="lic_man_agent"
                  defaultname="ubp_lic_man"
                  pubport="22057"
                  dealport="22058"
                  ip_type="0" />
    <ServiceTypeA type="mrs_vgw_agent"
                  defaultname="ubp_mrs_vgw"
                  pubport="22060"
                  dealport="22061"
                  ip_type="0" />
    <ServiceTypeA type="sds_adapter_agent"
                  defaultname="ubp_sds_adapter"
                  pubport="22063"
                  dealport="22064"
                  ip_type="1" />
    <ServiceTypeA type="mrs_node_mgr_agent"
                  defaultname="ubp_mrs_node_mgr"
                  pubport="22066"
                  dealport="22067"
                  ip_type="0" />
    <ServiceTypeA type="mrs_rec_man_agent"
                  defaultname="ubp_mrs_rec_man"
                  pubport="22069"
                  dealport="22070"
                  ip_type="0" />
    <ServiceTypeA type="mrs_rec_sinker_agent"
                  defaultname="ubp_mrs_rec_sinker"
                  pubport="22072"
                  dealport="22073"
                  ip_type="0" />
    <ServiceTypeA type="ue_agent"
                  defaultname="ubp_ue"
                  pubport="0"
                  dealport="9900"
                  ip_type="0" />
  </ServiceTypeInfo>
  <ServiceModeInfo>
    <ServiceMode name="MDC">
      <Service name="ubp_daem"/>
      <Service name="ubp_cm"/>
      <Service name="ubp_fm"/>
      <Service name="ubp_lm"/>
      <Service name="ubp_monitor"/>
      <Service name="ubp_lic_man"/>
      <Service name="ubp_sds_adapter" />
      <Service name="ubp_bcc"/>
      <Service name="ubp_bdc01"/>
      <Service name="ubp_dec_vgw"/>
    </ServiceMode>
    <ServiceMode name="MRS_C">
    	<Service name="ubp_daem"/>
      <Service name="ubp_cm"/>
      <Service name="ubp_fm"/>
      <Service name="ubp_lm"/>
      <Service name="ubp_monitor"/>
      <Service name="ubp_lic_man"/>
      <Service name="ubp_mrs_vgw"/>
      <Service name="ubp_mrs_node_mgr"/>
      <Service name="ubp_mrs_mgr"/>
      <Service name="ubp_mrs_rec_man"/>
      <Service name="ubp_mrs_rec_sinker"/>
    </ServiceMode>
    <ServiceMode name="MRS_D">
      <Service name="ubp_daem"/>
      <Service name="ubp_monitor"/>
      <Service name="ubp_mrs_vgw"/>
      <Service name="ubp_mrs_mgr"/>
      <Service name="ubp_mrs_rec_sinker"/>
    </ServiceMode>
    <ServiceMode name="MDC(BCC Only)">
      <Service name="ubp_daem"/>
      <Service name="ubp_cm"/>
      <Service name="ubp_fm"/>
      <Service name="ubp_lm"/>
      <Service name="ubp_monitor"/>
      <Service name="ubp_lic_man"/>
      <Service name="ubp_sds_adapter" />
      <Service name="ubp_bcc"/>
      <Service name="ubp_dec_vgw"/>
    </ServiceMode>
    <ServiceMode name="MDC(BDC Only)">
      <Service name="ubp_daem"/>
      <Service name="ubp_monitor"/>
      <Service name="ubp_bdc01"/>
    </ServiceMode>
    <ServiceMode name="MDC+MRS">
      <Service name="ubp_daem"/>
      <Service name="ubp_cm"/>
      <Service name="ubp_fm"/>
      <Service name="ubp_lm"/>
      <Service name="ubp_monitor"/>
      <Service name="ubp_lic_man"/>
      <Service name="ubp_sds_adapter" />
      <Service name="ubp_bcc"/>
      <Service name="ubp_bdc01"/>
      <Service name="ubp_dec_vgw"/>
      <Service name="ubp_mrs_vgw"/>
      <Service name="ubp_mrs_node_mgr"/>
      <Service name="ubp_mrs_mgr"/>
      <Service name="ubp_mrs_rec_man"/>
      <Service name="ubp_mrs_rec_sinker"/>
    </ServiceMode>
    
  </ServiceModeInfo>
</svcmgr:ServicePolicy>
